---
version: "2"
services:
  homeassistant:
    image: linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=Pacific/Auckland
      - PUID=1000 # User ID to run as
      - PGID=1000 # Group ID to run as
    volumes:
      - /ha_config:/config # Contains all relevant configuration files.